version: "3.3"
services:
  api:
    container_name: "api"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - logvolume01:/var/log
    depends_on:
      - mongodb
      - postgres

  mongodb:
    container_name: "mongo"
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db

  postgres:
    container_name: "postgres"
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  mongodb_data:
  postgres_data:
  logvolume01: