export enum EError {
  EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST',
  USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',

  PROFILE_NOT_CREATED = 'PROFILE_NOT_CREATED',
  NICKNAME_EXIST = 'NICKNAME_EXIST',

  DROPBOX_ERR = 'DROPBOX_ERR',
}
